# Generated by Django 3.2.3 on 2021-05-19 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trello', '0002_alter_project_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_task', to=settings.AUTH_USER_MODEL),
        ),
    ]
