# Generated by Django 3.2.3 on 2021-05-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0011_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateField(auto_now_add=True, verbose_name='Due date'),
        ),
    ]
